[package]
name = "rust-18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "*" 
phf = { version = "0.11", features = ["macros"]  }
queues = "1.0.2"